RARITY =
  common: {   name: 'common',   chance: 70, pokemon: [] },
  uncommon: { name: 'uncommon', chance: 25, pokemon: [] },
  rare: {     name: 'rare',     chance: 5,  pokemon: [] }

TYPE =
  electric: 'lightning',
  grass: 'grass',
  fire: 'fire',
  water: 'water',
  psychic: 'psychic',
  fighting: 'fighting',
  any: 'colorless'

POKEMON =
  '001': { name: 'Bulbasaur',       rarity: RARITY.common,      type: TYPE.grass },
  '002': { name: 'Ivysaur',         rarity: RARITY.uncommon,    type: TYPE.grass },
  '003': { name: 'Venusaur',        rarity: RARITY.rare,        type: TYPE.grass },
  '004': { name: 'Charmander',      rarity: RARITY.common,      type: TYPE.fire },
  '005': { name: 'Charmeleon',      rarity: RARITY.uncommon,    type: TYPE.fire },
  '006': { name: 'Charizard',       rarity: RARITY.rare,        type: TYPE.fire },
  '007': { name: 'Squirtle',        rarity: RARITY.common,      type: TYPE.water },
  '008': { name: 'Wartortle',       rarity: RARITY.uncommon,    type: TYPE.water },
  '009': { name: 'Blastoise',       rarity: RARITY.rare,        type: TYPE.water },
  '010': { name: 'Caterpie',        rarity: RARITY.common,      type: TYPE.grass },
  '011': { name: 'Metapod',         rarity: RARITY.common,      type: TYPE.grass },
  '012': { name: 'Butterfree',      rarity: RARITY.uncommon,    type: TYPE.grass },
  '013': { name: 'Weedle',          rarity: RARITY.common,      type: TYPE.grass },
  '014': { name: 'Kakuna',          rarity: RARITY.uncommon,    type: TYPE.grass },
  '015': { name: 'Beedrill',        rarity: RARITY.rare,        type: TYPE.grass },
  '016': { name: 'Pidgey',          rarity: RARITY.common,      type: TYPE.any },
  '017': { name: 'Pidgeotto',       rarity: RARITY.rare,        type: TYPE.any },
  '018': { name: 'Pidgeot',         rarity: RARITY.rare,        type: TYPE.any },
  '019': { name: 'Rattata',         rarity: RARITY.common,      type: TYPE.any },
  '020': { name: 'Raticate',        rarity: RARITY.uncommon,    type: TYPE.any },
  '021': { name: 'Spearow',         rarity: RARITY.common,      type: TYPE.any },
  '022': { name: 'Fearow',          rarity: RARITY.uncommon,    type: TYPE.any },
  '023': { name: 'Ekans',           rarity: RARITY.common,      type: TYPE.grass },
  '024': { name: 'Arbok',           rarity: RARITY.uncommon,    type: TYPE.grass },
  '025': { name: 'Pikachu',         rarity: RARITY.common,      type: TYPE.electric },
  '026': { name: 'Raichu',          rarity: RARITY.rare,        type: TYPE.electric },
  '027': { name: 'Sandshrew',       rarity: RARITY.common,      type: TYPE.fighting },
  '028': { name: 'Sandslash',       rarity: RARITY.uncommon,    type: TYPE.fighting },
  '029': { name: 'Nidoran♀',        rarity: RARITY.common,      type: TYPE.grass },
  '030': { name: 'Nidorina',        rarity: RARITY.uncommon,    type: TYPE.grass },
  '031': { name: 'Nidoqueen',       rarity: RARITY.rare,        type: TYPE.grass },
  '032': { name: 'Nidoran♂',        rarity: RARITY.common,      type: TYPE.grass },
  '033': { name: 'Nidorino',        rarity: RARITY.uncommon,    type: TYPE.grass },
  '034': { name: 'Nidoking',        rarity: RARITY.rare,        type: TYPE.grass },
  '035': { name: 'Clefairy',        rarity: RARITY.rare,        type: TYPE.any },
  '036': { name: 'Clefable',        rarity: RARITY.rare,        type: TYPE.any },
  '037': { name: 'Vulpix',          rarity: RARITY.common,      type: TYPE.fire },
  '038': { name: 'Ninetales',       rarity: RARITY.rare,        type: TYPE.fire },
  '039': { name: 'Jigglypuff',      rarity: RARITY.common,      type: TYPE.any },
  '040': { name: 'Wigglytuff',      rarity: RARITY.rare,        type: TYPE.any },
  '041': { name: 'Zubat',           rarity: RARITY.common,      type: TYPE.grass },
  '042': { name: 'Golbat',          rarity: RARITY.uncommon,    type: TYPE.grass },
  '043': { name: 'Oddish',          rarity: RARITY.common,      type: TYPE.grass },
  '044': { name: 'Gloom',           rarity: RARITY.uncommon,    type: TYPE.grass },
  '045': { name: 'Vileplume',       rarity: RARITY.rare,        type: TYPE.grass },
  '046': { name: 'Paras',           rarity: RARITY.common,      type: TYPE.grass },
  '047': { name: 'Parasect',        rarity: RARITY.uncommon,    type: TYPE.grass },
  '048': { name: 'Venonat',         rarity: RARITY.common,      type: TYPE.grass },
  '049': { name: 'Venomoth',        rarity: RARITY.rare,        type: TYPE.grass },
  '050': { name: 'Diglett',         rarity: RARITY.common,      type: TYPE.fighting },
  '051': { name: 'Dugtrio',         rarity: RARITY.rare,        type: TYPE.fighting },
  '052': { name: 'Meowth',          rarity: RARITY.common,      type: TYPE.any },
  '053': { name: 'Persian',         rarity: RARITY.uncommon,    type: TYPE.any },
  '054': { name: 'Psyduck',         rarity: RARITY.common,      type: TYPE.water },
  '055': { name: 'Golduck',         rarity: RARITY.uncommon,    type: TYPE.water },
  '056': { name: 'Mankey',          rarity: RARITY.common,      type: TYPE.fighting },
  '057': { name: 'Primeape',        rarity: RARITY.uncommon,    type: TYPE.fighting },
  '058': { name: 'Growlithe',       rarity: RARITY.uncommon,    type: TYPE.fire },
  '059': { name: 'Arcanine',        rarity: RARITY.uncommon,    type: TYPE.fire },
  '060': { name: 'Poliwag',         rarity: RARITY.common,      type: TYPE.water },
  '061': { name: 'Poliwhirl',       rarity: RARITY.uncommon,    type: TYPE.water },
  '062': { name: 'Poliwrath',       rarity: RARITY.rare,        type: TYPE.water },
  '063': { name: 'Abra',            rarity: RARITY.common,      type: TYPE.psychic },
  '064': { name: 'Kadabra',         rarity: RARITY.uncommon,    type: TYPE.psychic },
  '065': { name: 'Alakazam',        rarity: RARITY.rare,        type: TYPE.psychic },
  '066': { name: 'Machop',          rarity: RARITY.common,      type: TYPE.fighting },
  '067': { name: 'Machoke',         rarity: RARITY.uncommon,    type: TYPE.fighting },
  '068': { name: 'Machamp',         rarity: RARITY.rare,        type: TYPE.fighting },
  '069': { name: 'Bellsprout',      rarity: RARITY.common,      type: TYPE.grass },
  '070': { name: 'Weepinbell',      rarity: RARITY.uncommon,    type: TYPE.grass },
  '071': { name: 'Victreebel',      rarity: RARITY.rare,        type: TYPE.grass },
  '072': { name: 'Tentacool',       rarity: RARITY.common,      type: TYPE.water },
  '073': { name: 'Tentacruel',      rarity: RARITY.uncommon,    type: TYPE.water },
  '074': { name: 'Geodude',         rarity: RARITY.common,      type: TYPE.fighting },
  '075': { name: 'Graveler',        rarity: RARITY.uncommon,    type: TYPE.fighting },
  '076': { name: 'Golem',           rarity: RARITY.rare,        type: TYPE.fighting },
  '077': { name: 'Ponyta',          rarity: RARITY.common,      type: TYPE.fire },
  '078': { name: 'Rapidash',        rarity: RARITY.uncommon,    type: TYPE.fire },
  '079': { name: 'Slowpoke',        rarity: RARITY.common,      type: TYPE.psychic },
  '080': { name: 'Slowbro',         rarity: RARITY.uncommon,    type: TYPE.psychic },
  '081': { name: 'Magnemite',       rarity: RARITY.common,      type: TYPE.electric },
  '082': { name: 'Magneton',        rarity: RARITY.rare,        type: TYPE.electric },
  '083': { name: 'Farfetch\'d',     rarity: RARITY.uncommon,    type: TYPE.any },
  '084': { name: 'Doduo',           rarity: RARITY.common,      type: TYPE.any }
  '085': { name: 'Dodrio',          rarity: RARITY.uncommon,    type: TYPE.any }
  '086': { name: 'Seel',            rarity: RARITY.uncommon,    type: TYPE.water },
  '087': { name: 'Dewgong',         rarity: RARITY.uncommon,    type: TYPE.water },
  '088': { name: 'Grimer',          rarity: RARITY.common,      type: TYPE.grass },
  '089': { name: 'Muk',             rarity: RARITY.rare,        type: TYPE.grass },
  '090': { name: 'Shellder',        rarity: RARITY.common,      type: TYPE.water },
  '091': { name: 'Cloyster',        rarity: RARITY.uncommon,    type: TYPE.water },
  '092': { name: 'Gastly',          rarity: RARITY.common,      type: TYPE.psychic },
  '093': { name: 'Haunter',         rarity: RARITY.uncommon,    type: TYPE.psychic },
  '094': { name: 'Gengar',          rarity: RARITY.rare,        type: TYPE.psychic },
  '095': { name: 'Onix',            rarity: RARITY.common,      type: TYPE.fighting },
  '096': { name: 'Drowzee',         rarity: RARITY.common,      type: TYPE.psychic },
  '097': { name: 'Hypno',           rarity: RARITY.rare,        type: TYPE.psychic },
  '098': { name: 'Krabby',          rarity: RARITY.common,      type: TYPE.water },
  '099': { name: 'Kingler',         rarity: RARITY.uncommon,    type: TYPE.water },
  '100': { name: 'Voltorb',         rarity: RARITY.common,      type: TYPE.electric },
  '101': { name: 'Electrode',       rarity: RARITY.rare,        type: TYPE.electric },
  '102': { name: 'Exeggcute',       rarity: RARITY.common,      type: TYPE.grass },
  '103': { name: 'Exeggutor',       rarity: RARITY.uncommon,    type: TYPE.grass },
  '104': { name: 'Cubone',          rarity: RARITY.common,      type: TYPE.fighting },
  '105': { name: 'Marowak',         rarity: RARITY.uncommon,    type: TYPE.fighting },
  '106': { name: 'Hitmonlee',       rarity: RARITY.rare,        type: TYPE.fighting },
  '107': { name: 'Hitmonchan',      rarity: RARITY.rare,        type: TYPE.fighting },
  '108': { name: 'Lickitung',       rarity: RARITY.uncommon,    type: TYPE.any },
  '109': { name: 'Koffing',         rarity: RARITY.common,      type: TYPE.grass },
  '110': { name: 'Weezing',         rarity: RARITY.uncommon,    type: TYPE.grass },
  '111': { name: 'Rhyhorn',         rarity: RARITY.common,      type: TYPE.fighting },
  '112': { name: 'Rhydon',          rarity: RARITY.uncommon,    type: TYPE.fighting },
  '113': { name: 'Chansey',         rarity: RARITY.rare,        type: TYPE.any },
  '114': { name: 'Tangela',         rarity: RARITY.common,      type: TYPE.grass },
  '115': { name: 'Kangaskhan',      rarity: RARITY.rare,        type: TYPE.any },
  '116': { name: 'Horsea',          rarity: RARITY.common,      type: TYPE.water },
  '117': { name: 'Seadra',          rarity: RARITY.uncommon,    type: TYPE.water },
  '118': { name: 'Goldeen',         rarity: RARITY.common,      type: TYPE.water },
  '119': { name: 'Seaking',         rarity: RARITY.uncommon,    type: TYPE.water },
  '120': { name: 'Staryu',          rarity: RARITY.common,      type: TYPE.water },
  '121': { name: 'Starmie',         rarity: RARITY.common,      type: TYPE.water },
  '122': { name: 'Mr. Mime',        rarity: RARITY.rare,        type: TYPE.psychic },
  '123': { name: 'Scyther',         rarity: RARITY.rare,        type: TYPE.grass },
  '124': { name: 'Jynx',            rarity: RARITY.uncommon,    type: TYPE.psychic },
  '125': { name: 'Electabuzz',      rarity: RARITY.rare,        type: TYPE.electric },
  '126': { name: 'Magmar',          rarity: RARITY.uncommon,    type: TYPE.fire },
  '127': { name: 'Pinsir',          rarity: RARITY.rare,        type: TYPE.grass },
  '128': { name: 'Tauros',          rarity: RARITY.uncommon,    type: TYPE.any },
  '129': { name: 'Magikarp',        rarity: RARITY.uncommon,    type: TYPE.water },
  '130': { name: 'Gyarados',        rarity: RARITY.rare,        type: TYPE.water },
  '131': { name: 'Lapras',          rarity: RARITY.rare,        type: TYPE.water },
  '132': { name: 'Ditto',           rarity: RARITY.rare,        type: TYPE.any },
  '133': { name: 'Eevee',           rarity: RARITY.common,      type: TYPE.any },
  '134': { name: 'Vaporeon',        rarity: RARITY.rare,        type: TYPE.water },
  '135': { name: 'Jolteon',         rarity: RARITY.rare,        type: TYPE.electric },
  '136': { name: 'Flareon',         rarity: RARITY.rare,        type: TYPE.fire },
  '137': { name: 'Porygon',         rarity: RARITY.uncommon,    type: TYPE.any },
  '138': { name: 'Omanyte',         rarity: RARITY.common,      type: TYPE.water },
  '139': { name: 'Omastar',         rarity: RARITY.uncommon,    type: TYPE.water },
  '140': { name: 'Kabuto',          rarity: RARITY.common,      type: TYPE.fighting },
  '141': { name: 'Kabutops',        rarity: RARITY.rare,        type: TYPE.fighting },
  '142': { name: 'Aerodactyl',      rarity: RARITY.rare,        type: TYPE.fighting },
  '143': { name: 'Snorlax',         rarity: RARITY.rare,        type: TYPE.any },
  '144': { name: 'Articuno',        rarity: RARITY.rare,        type: TYPE.water },
  '145': { name: 'Zapdos',          rarity: RARITY.rare,        type: TYPE.electric },
  '146': { name: 'Moltres',         rarity: RARITY.rare,        type: TYPE.fire },
  '147': { name: 'Dratini',         rarity: RARITY.uncommon,    type: TYPE.any },
  '148': { name: 'Dragonair',       rarity: RARITY.rare,        type: TYPE.any },
  '149': { name: 'Dragonite',       rarity: RARITY.rare,        type: TYPE.any },
  '150': { name: 'Mewtwo',          rarity: RARITY.rare,        type: TYPE.psychic }
  '151': { name: 'Mew',             rarity: RARITY.rare,        type: TYPE.psychic }

module.exports =
  RARITY: RARITY,
  TYPE: TYPE,
  POKEMON: POKEMON
